spring:
  application:
    name: loja
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
